name: 'Tests: node.js (18+)'

on: [pull_request, push]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: majors
          preset: '>=18'

  latest:
    needs: [matrix]
    name: 'latest majors'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        eslint:
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 4.14 # last version without messageId
          - 3
        babel-eslint:
          - 10
          - 9
          - 8
        typescript-eslint:
          - 5
          - 6
          - 7
          - 8
        exclude:
          - eslint: 3
            babel-eslint: 10
          - eslint: 3
            typescript-eslint: 5
          - eslint: 4
            typescript-eslint: 5
          - eslint: 4.14
            typescript-eslint: 5
          - eslint: 5
            typescript-eslint: 5
          - eslint: 3
            typescript-eslint: 6
          - eslint: 4
            typescript-eslint: 6
          - eslint: 4.14
            typescript-eslint: 6
          - eslint: 5
            typescript-eslint: 6
          - eslint: 6
            typescript-eslint: 6
          - eslint: 9
            typescript-eslint: 6
          - eslint: 3
            typescript-eslint: 7
          - eslint: 4
            typescript-eslint: 7
          - eslint: 4.14
            typescript-eslint: 7
          - eslint: 5
            typescript-eslint: 7
          - eslint: 6
            typescript-eslint: 7
          - eslint: 7
            typescript-eslint: 7
          - eslint: 9
            typescript-eslint: 7
          - eslint: 3
            typescript-eslint: 8
          - eslint: 4
            typescript-eslint: 8
          - eslint: 4.14
            typescript-eslint: 8
          - eslint: 5
            typescript-eslint: 8
          - eslint: 6
            typescript-eslint: 8
          - eslint: 7
            typescript-eslint: 8
          - eslint: 9
            typescript-eslint: 5
          - node-version: 19
            typescript-eslint: 7

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install ${{ matrix.node-version }} && npm install'
        with:
          node-version: ${{ matrix.node-version }}
          after_install: |
            npm install --no-save "eslint@${{ matrix.eslint }}" "@typescript-eslint/parser@${{ matrix.typescript-eslint }}" "babel-eslint@${{ matrix.babel-eslint }}"
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: "${{ matrix.typescript-eslint >= 6 && 'false' || 'true' }}"
      - run: npx ls-engines
      - run: npm run unit-test
      - uses: codecov/codecov-action@v3.1.5

  node:
    name: 'node 18+'
    needs: [latest]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
