name: 'Tests: readme'

on: [pull_request, push]

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/actions/node/install@main
        name: 'nvm install lts/* && npm install'
        with:
          node-version: 'lts/*'
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
      - run: npm run generate-list-of-rules:check
