name: Smoke test

on:
  schedule:
    - cron: '0 0 * * SUN'
  workflow_dispatch:

jobs:
  smoke-test:
    if: ${{ github.repository == 'jsx-eslint/eslint-plugin-react' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        name: 'nvm install lts/* && npm install'
        with:
          node-version: 'lts/*'
          skip-ls-check: true
      - run: |
          npm link
          npm link eslint-plugin-react
      - uses: AriPerkkio/eslint-remote-tester-run-action@v4
        with:
          issue-title: 'Results of weekly scheduled smoke test'
          issue-label: 'smoke-test'
          eslint-remote-tester-config: test/eslint-remote-tester.config.js
